run_name: OLMo-180M-ce-1024-books
seed: 6198
dry_run: false

wandb:
  entity: messi-hua
  name: ${run_name}
  project: olmo-tiny

model:
  d_model: 1024
  n_heads: 8
  n_layers: 8
  mlp_ratio: 8
  weight_tying: false
  alibi: false
  rope: true
  fourier: false
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: false
  clip_qkv: null
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 1024
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 1
  init_device: cuda
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3

ddp:
  grad_sync_mode: batch
  find_unused_params: false

compile: null

optimizer:
  name: adamw
  learning_rate: 6.0e-4
  weight_decay: 0.1
  eps: 1e-8
  decay_norm_and_bias: true
  decay_embeddings: true
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 10000
  alpha_f: 0.1
  warmup_min_lr: 0

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: workspace/${run_name}  # doesn't matter since we'll upload to S3
remote_save_folder: null
save_overwrite: true

# Unsharded checkpoints (for ddp)
save_interval_unsharded: 5000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 1ep
global_train_batch_size: 512
device_train_microbatch_size: 16

precision: amp_bf16
distributed_strategy: ddp

gen1_gc_interval: 1

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: 1000
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: all-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
  - label: all_small-ppl-validation-128
    data:
      device_eval_batch_size: 64
      num_workers: 0
      drop_last: true
      chunk_size: 128
      datasets:
        v3-small-c4_en-validation-128:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
  - label: all_small-ppl-validation-256
    data:
      device_eval_batch_size: 32
      num_workers: 0
      drop_last: true
      chunk_size: 256
      datasets:
        v3-small-c4_en-validation-256:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
  - label: all_small-ppl-validation-512
    data:
      device_eval_batch_size: 16
      num_workers: 0
      drop_last: true
      chunk_size: 512
      datasets:
        v3-small-c4_en-validation-512:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
  - label: all_small-ppl-validation-1024
    data:
      device_eval_batch_size: 8
      num_workers: 0
      drop_last: true
      chunk_size: 1024
      datasets:
        v3-small-c4_en-validation-1024:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
  - label: all_small-ppl-validation-2048
    data:
      device_eval_batch_size: 4
      num_workers: 0
      drop_last: true
      chunk_size: 2048
      datasets:
        v3-small-c4_en-validation-2048:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
  - label: all_small-ppl-validation-4096
    data:
      device_eval_batch_size: 2
      num_workers: 0
      drop_last: true
      chunk_size: 4096
      datasets:
        v3-small-c4_en-validation-4096:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
  - label: all_small-ppl-validation-8192
    data:
      device_eval_batch_size: 1
      num_workers: 0
      drop_last: true
      chunk_size: 8192
      datasets:
        v3-small-c4_en-validation-8192:
          - /root/data/OLMo/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream
 
  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  - label: commonsense_qa
    type: downstream

  - label: social_iqa
    type: downstream

  # Doesn't work from cache.
  # - label: basic_arithmetic
  #   type: downstream

  # - label: mmlu_stem_var
  #   type: downstream

  # - label: mmlu_humanities_var
  #   type: downstream

  # - label: mmlu_social_sciences_var
  #   type: downstream

  # - label: mmlu_other_var
  #   type: downstream

  # - label: mmlu_stem_mc_5shot
  #   type: downstream

  # - label: mmlu_humanities_mc_5shot
  #   type: downstream

  # - label: mmlu_social_sciences_mc_5shot
  #   type: downstream

  # - label: mmlu_other_mc_5shot
  #   type: downstream

  # - label: mmlu_stem_mc_5shot_test
  #   type: downstream

  # - label: mmlu_humanities_mc_5shot_test
  #   type: downstream

  # - label: mmlu_social_sciences_mc_5shot_test
  #   type: downstream

  # - label: mmlu_other_mc_5shot_test
  #   type: downstream

  - label: basic_arithmetic
    type: downstream

  - label: trivia_qa_wiki_ppl
    type: downstream

  - label: natural_qs_open_ppl
    type: downstream

  - label: arc_easy_ppl
    type: downstream

data:
  pad_direction: right
  num_workers: 32
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    ######### NON WEB DATA #########
    # ~> GUTENBERG BOOKS (5.256 GT)
    - /root/data/OLMo/preprocessed/olmo-mix/v1_6-decontaminated/books/gpt-neox-olmo-dolma-v1_5/part-0-00000.npy
    - /root/data/OLMo/preprocessed/olmo-mix/v1_6-decontaminated/books/gpt-neox-olmo-dolma-v1_5/part-1-00000.npy
    - /root/data/OLMo/preprocessed/olmo-mix/v1_6-decontaminated/books/gpt-neox-olmo-dolma-v1_5/part-2-00000.npy